server:
  port: 8081
  servlet:
    context-path: ${CONTEXT_PATH}
spring:
  application:
    name: BE-SG-TN
  profiles:
    active: ${PROFILE}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL}
    password: ${PASSWORD_EMAIL}
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          port: 25
          auth: true
          starttls:
            enable: true
            required: true
          connectionTimeout: 5000
          sendTimeout: 3000
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
logging:
  level:
    root: INFO
    org.springframework: INFO
    org.springframework.web: DEBUG  # Hiển thị log chi tiết của request
    org.hibernate: ERROR  # Giảm log Hibernate (nếu có)
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  org:
    hibernate:
      SQL_SLOW: info
    springframework:
      security: ERROR
application:
  security:
    authentication:
      jwt:
        base64-secret: ${BASE64_SECRET_KEY}
        token-validity-in-seconds: 3600
        token-validity-in-seconds-for-remember-me: 2592000
        refresh-token-validity-in-seconds: 2592000

fcm:
  serviceAccountKey: ./firebase/sgtm-backend-firebase-adminsdk-fbsvc-9c38a85b77.json